config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username),
                                                ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_USERNAME'])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password),
                                                  ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_PASSWORD']))
  end
  mount Sidekiq::Web, at: '/sidekiq'

  # Devise
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show]
  post '/users/update', to: 'users#update'
  post '/users/cancel_subscription', to: 'users#cancel_subscription'

  resources :donations, only: %i[create show new]
  resources :payment_intents
  resources :fmpages, only: [:show]

  root to: 'pages#home'
  post 'send_contact' => 'pages#send_contact'
end

app/views/shared/_donation.html.erb
<section class="donation-cards-container bg-light py-5" id="donate">
  <div class="container px-4 px-lg-5" >
    <h2 class="text-black mb-4">
      <%= @sitewide_text_items.find_by(name: "support us")[I18n.locale.to_s].titleize %>
    </h2>
    <div class="row gx-4 gx-lg-5">
      
      <div class="col-md-4 mb-3 mb-md-0">
        <div class="card py-4 h-100 bg-white" style="box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
          <div class="card-body text-center">
              <i class="fa-regular fa-credit-card"></i> / <i class="fa-solid fa-money-bill-wave"></i>
              <h4 class="text-uppercase m-0"><%= @sitewide_text_items.find_by(name: "$20 month")[I18n.locale.to_s] %></h4>
              <h4 class="text-uppercase m-0 mt-2"><%= t("this_payment_is_for_one_month") %></h4>
              <hr class="my-4 mx-auto" />
              <div class="small text-black-50">-</div>
              
              <%= link_to t("$sum_/_month"), new_donation_path(:donation_type => "monthly_subscription"), class: "btn btn-primary mb-2 fundme-button-link" %>
          </div>
        </div>
      </div>

      <div class="col-md-4 mb-3 mb-md-0">
        <div class="card py-4 h-100 bg-white" style="box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
          <div class="card-body text-center">
            <i class="fa-regular fa-credit-card"></i> / <i class="fa-solid fa-money-bill-wave"></i>
            <h4 class="text-uppercase m-0"><%= @sitewide_text_items.find_by(name: "$200 year")[I18n.locale.to_s] %></h4>
            <h4 class="text-uppercase m-0 mt-2"><%= t("this_payment_is_for_one_year") %></h4>
            <hr class="my-4 mx-auto" />
            <div class="small text-black-50">-</div>
            
            <%= link_to t("$sum_/_year"), new_donation_path(:donation_type => "yearly_subscription"), class: "btn btn-primary mb-2 fundme-button-link" %>
          </div>
        </div>
      </div>

      <div class="col-md-4 mb-3 mb-md-0">
        <div class="card py-4 h-100 bg-white" style="box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
          <div class="card-body text-center">
            <i class="fa-regular fa-credit-card"></i> / <i class="fa-solid fa-money-bill-wave"></i>
            <h4 class="text-uppercase m-0 mt-4"><%= @sitewide_text_items.find_by(name: "one time donation")[I18n.locale.to_s] %></h4>
            <hr class="my-4 mx-auto" />
            <div class="small text-black-50">-</div>

            <%= link_to t("one_time_donation"), new_donation_path(:sub_amount => 0), class: "btn btn-primary mb-2 fundme-button-link" %>
          </div>
        </div>
      </div>

    </div>
    <p class="text-white-50 mt-5"><%= @sitewide_text_items.find_by(name: "payment advice")[I18n.locale.to_s] %></p>
  </div>
</section>

app/views/shared/_donation_history.html.erb
<section class="account-section text-center pb-5 bg-light" id="about" style="padding-top: 0rem;">
    <div class="container px-4 px-lg-5" style=";">
        <div class="row gx-4 gx-lg-5">
            <div class="col-md-12  mb-md-0 my-3">
                <div class="card py-4 h-100" style="box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;">
                    <div class="card-body text-center">
                        <i class="fa-solid fa-chart-line"></i>
                        <h4 class="text-uppercase m-0"><%= t("donation_history") %></h4>
                        <hr class="my-4 mx-auto" />
                        <div class="small text-black-50 text-start">
                            <% if @user.donations.count == 0 %>
                                <%= "No donations made so far" %>
                            <% else %>
                                <div style="overflow-x:auto;">
                                    <table>
                                        <tr class="spaceUnder">
                                            <th><%= t("payment_time") %></th>
                                            <th><%= t("stripe_payment_reference") %></th>
                                            <th><%= t("amount") %></th>
                                            <th><%= t("type") %></th>
                                            <th><%= t("status") %></th>
                                        </tr>
                                        <% @user.donations.all.sort_by { |h| h[:created_at] }.reverse.each do |donation| %>
                                            <%# @user.donations.all.reverse.each do |donation| %>
                                                <%# if donation.donation_type == "one_time" %>
                                                    <tr class="spaceUnder">
                                                        <td><%= donation.created_at %></td>
                                                        <td><%= donation.stripe_payment_id %></td>
                                                        <td><%= "$#{donation.amount}" %></td>
                                                        <td>
                                                            <% if donation.donation_type == "monthly_subscription" || donation.donation_type == "yearly_subscription" || donation.donation_type == "automated" %>
                                                                <% if donation.amount == 20 %>
                                                                    <%= "#{@user.subscription_frequency.capitalize} #{t("subscription")} #{donation.subscription_set_number} / 12" %>
                                                                <% else %>
                                                                    <%= "#{@user.subscription_frequency.capitalize} #{t("subscription")} 1 / 1" %>
                                                                <% end %>
                                                            <% else %>
                                                                <%= "one time payment" %>
                                                            <% end %>
                                                        </td>
                                                        <td><%= donation.status %></td>
                                                    </tr>
                                            <%# end %>
                                        <% end %>
                                    </table>
                                </div>
                            <% end %>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<section class="bg-black">
    <footer class="bg-black small text-center text-white-50" style="margin-bottom: 0px;">
        <div class="container px-4 px-lg-5">Copyright &copy; FundMe.org 2022</div>
    </footer>
</section>

app/views/shared/_navbar.html.erb
 <!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light fixed-top navbar-backfade" id="top-nav-bar">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href=
            <% if params[:controller] == "pages" && params[:action] == "home" %>
                <%= "#page-top" %>
            <% else %>
                <%= "/" %>
            <% end %>>
                fundme
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
            <% if params[:controller] == "pages" && params[:action] == "home" %>
                <!-- <li class="nav-item"><a class="nav-link" href="#about"><%= t("about") %></a></li> -->
                <!-- <li class="nav-item"><a class="nav-link" href="#immigrationlaw"><%= t("immigration_law") %></a></li> -->
                <!--<li class="nav-item"><a class="nav-link" href="#contactus"><%= t("contact") %></a></li>  -->

            <% end %>
                <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to current_user, class: "nav-link", style: ""  do %>
                            <i class="fa-solid fa-circle-user" style="margin-right: 5px;"></i><%= current_user.username %>
                            <%# raise %>
                        <% end %>
                    </li>

                    <li class="nav-item">
                        <%= link_to destroy_user_session_path, method: :delete, class: "nav-link", style: ""  do %>
                            <i class="fa-solid fa-right-from-bracket" style="margin-right: 5px;"></i><span id="logout-text"><%= t("log_out") %></span>
                        <% end %>
                    </li>
                <% else %>
                    <!-- <li class="nav-item">  -->
                        <%= link_to new_user_session_path, class: "nav-link", style: ""  do %>
                            <i class="fa-solid fa-circle-user"></i> <%= t("login_sign_up") %>
                        <% end %>
                    <!-- </li>  -->
                <% end %>


                <!-- New dropdown -->
                <li class="nav-item" style="float: right; display: inline-block; position: relative; min-width: 180px;">
                    <ul id="mobile-language-select" class="mobile-language-select" style="">
                        <li style="margin-left: 0px; float: left;">
                            <a class="nav-link" ><%= t("sections") %></a>
                        </li>

                        <% if params[:controller] == "pages" && params[:action] == "home" %>
                            <li><a class="nav-link" href="#about"><%= t("about").capitalize %></a></li>
                            <li><a class="nav-link" href="#donate"><%= t("donate").capitalize %></a></li>
                        <% else %>
                            <li><a class="nav-link" href="/donations/new"><%= t("donate").capitalize %></a></li>
                        <% end %>



                        <% Fmpage.all.each do |page| %>
                            <% if page.is_published? %>
                                <% if page.title == "home" %>
                                    <li><a class="nav-link" href="/?lang=<%= I18n.locale.to_s %>"><%= page[I18n.locale].capitalize %></a></li>
                                    <%# raise %>
                                <% else %>
                                    <li><a class="nav-link" href="/fmpages/<%= page.title %>?lang=<%= I18n.locale.to_s %>"><%= page[I18n.locale].capitalize %></a></li>
                                <% end %>

                            <% end %>
                        <% end %>
                        <% if params[:controller] == "pages" && params[:action] == "home" %>
                            <li><a class="nav-link" href="#contactus"><%= t("contact").capitalize %></a></li>
                        <% else %>
                            <li><a class="nav-link" href="/?lang=<%= I18n.locale.to_s %>#contactus"><%= t("contact").capitalize %></a></li>
                        <% end %>

                    </ul>

                    <!-- custom dropdown -->
                        <!-- position fixed square -->
                        <div id="dropdown-language-select" class="ro-button-useroptions-inner-container">
                            <a class="dropdown-item nav-link"><%= t("sections").capitalize %>:</a>
                            <ul id="useroptions-dropdown-menu" class="ro-button-useroptions-cssdropdown-content ddNavDropDownMenus" style="padding-left: 0px; float: left; text-align: left;">

                                <% if params[:controller] == "pages" && params[:action] == "home" %>
                                    <li><a class="dropdown-item" href="#about"><%= t("about").capitalize %></a></li>
                                    <li><a class="dropdown-item" href="#donate"><%= t("donate").capitalize %></a></li>
                                <% else %>
                                    <li><a class="dropdown-item" href="/donations/new"><%= t("donate").capitalize %></a></li>
                                <% end %>
                                    <% Fmpage.all.each do |page| %>
                                    <% if page.is_published? %>
                                        <% if page.title == "home" %>
                                            <li><a class="dropdown-item" href="/?lang=<%= I18n.locale.to_s %>"><%= page[I18n.locale].capitalize %></a></li>
                                        <% else %>
                                            <li><a class="dropdown-item" href="/fmpages/<%= page.title %>?lang=<%= I18n.locale.to_s %>"><%= page[I18n.locale].capitalize %></a></li>
                                        <% end %>

                                    <% end %>
                                <% end %>
                                <% if params[:controller] == "pages" && params[:action] == "home" %>
                                    <li><a class="dropdown-item" href="#contactus"><%= t("contact").capitalize %></a></li>
                                <% else %>
                                    <li><a class="dropdown-item" href="/?lang=<%= I18n.locale.to_s %>#contactus"><%= t("contact").capitalize %></a></li>
                                <% end %>

                            </ul>
                            <!-- button is z-indexed above everything else and given 0 opacity -->
                            <div id="useroptions-dropdown" class="ro-button-useroptions-cssdropbtn dropdown-button"></div>
                        </div>
                </li>


                <!-- old dropdown -->
                <li class="nav-item" style="float: right; display: inline-block; position: relative;">
                        <% languages = ["en", "es", "pt"] %>
                        <% languages.delete(I18n.locale.to_s) %>
                        <%# raise %>
                    <ul id="mobile-language-select" class="mobile-language-select" style="">
                        <li style="margin-left: 0px; float: left;">
                            <a class="nav-link" ><i class="fa-solid fa-globe" style=""></i><%= I18n.locale %></a>
                        </li>
                        <%# raise %>
                        <li><a class="nav-link" href="<%= request.path %>?lang=<%= languages[0] %>" ><i class="fa-solid fa-globe"></i><%= languages[0] %></a></li>
                        <li><a class="nav-link" href="<%= request.path %>?lang=<%= languages[1] %>" ><i class="fa-solid fa-globe"></i><%= languages[1] %></a></li>
                        <!-- <li><a class="nav-link" href="<%= request.path %>?lang=<%= languages[2] %>" ><i class="fa-solid fa-globe"></i><%= languages[2] %></a></li> -->
                    </ul>

                    <!-- custom dropdown -->
                    <!-- position fixed square -->
                    <div id="dropdown-language-select" class="ro-button-useroptions-inner-container">
                        <a class="dropdown-item nav-link"><i class="fa-solid fa-globe"></i><%= I18n.locale %></a>
                        <ul id="lang_options-dropdown-menu" class="ro-button-useroptions-cssdropdown-content ddNavDropDownMenus" style="padding-left: 0px;">
                            <li><a class="dropdown-item" href="<%= request.path %>?lang=<%= languages[0] %>"><i class="fa-solid fa-globe"></i><%= languages[0] %></a></li>
                            <li><a class="dropdown-item" href="<%= request.path %>?lang=<%= languages[1] %>"><i class="fa-solid fa-globe"></i><%= languages[1] %></a></li>
                            <!-- <li><a class="dropdown-item" href="<%= request.path %>?lang=<%= languages[2] %>"><i class="fa-solid fa-globe"></i><%= languages[2] %></a></li> -->
                        </ul>
                        <!-- button is z-indexed above everything else and given 0 opacity -->
                        <div id="" class="ro-button-useroptions-cssdropbtn dropdown-button"></div>
                    </div>
                </li>


            </ul>
        </div>
    </div>
</nav>